### PR TITLE
fix: drop mutex guard when DuplexStream I/O op is pending

### LINKED ISSUE #7: DuplexStream pending I/O keeps holding the `Mutex`
For `DuplexStream`, if an I/O operation is pending, the async task will always hold  the inner `Mutex` guard, then when we try to access the inner `SimplexStream` when dropping `DuplexStream`, deadlock happens:

```toml
monoio-duplex = { git = "https://github.com/SteveLauC/monoio-duplex", rev = "baf540ae2c155e6b86eb26e99a9f05dff789aa64" }
```

```rs
use monoio::io::AsyncReadRent;
use monoio_duplex::duplex::duplex;

#[monoio::main(enable_timer = true)]
async fn main() {
    let (mut client, server) = duplex(100);
    let (tx, rx) = tokio::sync::oneshot::channel::<()>();

    monoio::spawn(async move {
        tx.send(()).unwrap();
        let (_result, _buf) = client.read(vec![0_u8; 10]).await;
    });

    rx.await.unwrap();

    drop(server);
}
```

The above code snippet blocks forever.

### PR DESCRIPTION
**Pull request by SteveLauC**
### What does this PR do

1. Fixes the issue described in #7, closes #7.
2. Replaces `async_lock::Mutex` with `std::sync::Mutex` because:
    1. We have ensured that a lock guard will be held across an await point.
    2. Using blocking Mutex in a single-threaded runtime like Monoio won't harm performance, as only 1 async task can  executed at any time.
    3. Using async Mutex forces us to handle async operations in `Drop`, I used `futures::executor::block_on()` before this PR, but it is [dangerous](https://github.com/bytedance/monoio/discussions/312) and can lead to deadlock with careless mistakes.
3. 2 tests are added to ensure #7 won't happen again.

### CODE REVIEW

File: src/duplex.rs [hunk 1]
```diff
@@ -78,48 +79,90 @@ pub struct DuplexStream {
...
+    ($trait:ident, $function:ident, $guard:expr) => {{
+        let opt_read_ready = <SimplexStream as $trait>::$function(&mut *$guard).now_or_never();
+
+        match opt_read_ready {
+            Some(result) => result,
+            None => {
+                // drop the Mutex guard or it could deadlock
+                // https://github.com/SteveLauC/monoio-duplex/issues/7
+                drop($guard);
+                std::future::pending().await
```
Comment (SteveLauC) [inline src/duplex.rs:104]: Future polls to this future will always return Pending due to this line, the state of this future has been changed, which should never be done!
